# **NUMPY**

### Basic Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.5,"aditya"]
a

[1, 2, 3.5, 'aditya']

In [4]:
np.array(a)

array(['1', '2', '3.5', 'aditya'], dtype='<U32')

> Vectors (1D)

In [5]:
array1 = [1,2,3,4]
array1

[1, 2, 3, 4]

> Metrices (2D)

In [6]:
l = [
    [1,2,3],
    [4,5,6],
    [6,7,8]
]
l

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

> Tensors (3D)

In [7]:
j = [
    [
        [1,2,3],
        [3,2,1],
    ],
    [
        [4,5,6],
        [6,5,4],
    ],
    [
        [7,8,9],
        [9,8,7]
    ]
]
j

[[[1, 2, 3], [3, 2, 1]], [[4, 5, 6], [6, 5, 4]], [[7, 8, 9], [9, 8, 7]]]

### Array Generation Function

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Random Generation Function

In [13]:
np.random.rand(10)

array([0.55745841, 0.89171032, 0.77219295, 0.25653057, 0.98405995,
       0.33413039, 0.15257118, 0.62484378, 0.63991461, 0.17716096])

In [14]:
np.random.randn(4)

array([-0.52584443,  0.50810285,  0.86846481,  1.70738829])

In [15]:
np.random.randint(10,20)

10

In [16]:
np.random.randint(1,20,10)

array([14,  1, 19, 18, 13,  9,  5,  9, 11, 13], dtype=int32)

### Array Attribute

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

### Array Method

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [26]:
np.sum(arr, axis=0)

array([12, 15, 18])

### Reshape and Resizing

In [27]:
arr = np.arange(1,37)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [28]:
arr = arr.reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### Indexing and Slicing

In [29]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
arr[6]

np.int64(17)

In [31]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [32]:
arr[0:4:3]

array([11, 14])

### Numpy Indxing and Sclicing of Matrix

In [33]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [34]:
arr[3] 

array([19, 20, 21, 22, 23, 24])

In [35]:
arr[:,3]

array([ 4, 10, 16, 22, 28])

In [36]:
arr[4,5]

np.int64(30)

### Boolean Indexing

In [37]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
boolean_indexing1 = arr % 2 == 0
boolean_indexing1

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [39]:
boolean_indexing2 = arr % 2 != 0
boolean_indexing2

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [40]:
arr = arr[boolean_indexing1]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Numpy Array Operations

> Arithmatic Operations

In [41]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])

In [42]:
a3 = a1 + a2
a3

array([ 2,  4,  6,  8, 10])

In [43]:
a4 = a1 ** a2
a4

array([   1,    4,   27,  256, 3125])

> Broadcasting

In [44]:
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [45]:
arr + 10

array([11, 12, 13, 14, 15, 16])

> Deep and Shallow Copy

In [46]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [48]:
a #deep copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
b = a.copy()
b  #shallow cpopy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
b[0] = 1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

> Matrix Operations

In [51]:
A = np.array(([1,2],[3,4]))
B = np.array(([4,5],[6,7]))

In [52]:
A

array([[1, 2],
       [3, 4]])

In [53]:
B

array([[4, 5],
       [6, 7]])

In [54]:
A * B

array([[ 4, 10],
       [18, 28]])

In [55]:
A @ B   #matrix multiplication

array([[16, 19],
       [36, 43]])

> Transpose

In [56]:
A.T

array([[1, 3],
       [2, 4]])

In [57]:
B.T

array([[4, 6],
       [5, 7]])

### Advance Array Manipulations

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
B

array([[4, 5],
       [6, 7]])

In [60]:
a = np.array([1,2,3,4])
b = np.array([5,5,6,8])

In [61]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 5, 6, 8]])

In [62]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 5, 6, 8])

In [63]:
np.column_stack((a,b))

array([[1, 5],
       [2, 5],
       [3, 6],
       [4, 8]])

### Splitting Array

In [64]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

**KHATAM**