# **NUMPY**

- Basic Array Operations

In [54]:
import numpy as np

In [55]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [56]:
a = [1,2,3.5,"aditya"]
a

[1, 2, 3.5, 'aditya']

In [57]:
np.array(a)

array(['1', '2', '3.5', 'aditya'], dtype='<U32')

> Vectors (1D)

In [58]:
array1 = [1,2,3,4]
array1

[1, 2, 3, 4]

> Metrices (2D)

In [59]:
l = [
    [1,2,3],
    [4,5,6],
    [6,7,8]
]
l

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

> Tensors (3D)

In [60]:
j = [
    [
        [1,2,3],
        [3,2,1],
    ],
    [
        [4,5,6],
        [6,5,4],
    ],
    [
        [7,8,9],
        [9,8,7]
    ]
]
j

[[[1, 2, 3], [3, 2, 1]], [[4, 5, 6], [6, 5, 4]], [[7, 8, 9], [9, 8, 7]]]

- Array Generation Function

In [61]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

- Random Generation Function

In [66]:
np.random.rand(10)

array([0.62163052, 0.88492041, 0.9424884 , 0.70378509, 0.03830568,
       0.65309879, 0.98652186, 0.7156254 , 0.19850959, 0.15012555])

In [67]:
np.random.randn(4)

array([0.22403147, 0.43393784, 1.7498539 , 0.34568902])

In [68]:
np.random.randint(10,20)

13

In [69]:
np.random.randint(1,20,10)

array([16,  2,  9, 10, 15,  8,  8,  7,  4,  3], dtype=int32)

- Array Attribute

In [70]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr.shape

(3, 3)

In [72]:
arr.size

9

In [73]:
arr.dtype

dtype('int64')

- Array Method

In [74]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr.min()

np.int64(1)

In [76]:
arr.max()

np.int64(9)

In [77]:
arr.sum()

np.int64(45)

In [78]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [79]:
np.sum(arr, axis=0)

array([12, 15, 18])

- Reshape and Resizing

In [80]:
arr = np.arange(1,37)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [81]:
arr = arr.reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

#Indexing and Slicing

In [82]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
arr[6]

np.int64(17)

In [84]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [85]:
arr[0:4:3]

array([11, 14])

- Numpy Indxing and Sclicing of Matrix

In [86]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [90]:
arr[3] 

array([19, 20, 21, 22, 23, 24])

In [88]:
arr[4,5]

np.int64(30)